name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Ubuntu ${{ matrix.flavor }} ${{ matrix.compiler.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flavor: [Release, Debug]
        compiler: [ {name: "GCC", cc: "gcc", cxx: "g++"}, {name: "Clang", cc: "clang", cxx: "clang++"} ]

    env:
      CMAKE_BUILD_TYPE: ${{ matrix.flavor }}
      CMAKE_CONFIG_TYPE: ${{ matrix.flavor }}
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
      BUILD_DIR: ${{github.workspace}}/build

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt update && sudo apt install -yq libpng++-dev

    - name: Configure CMake
      run: cmake -B ${{ env.BUILD_DIR }}

    - name: Build
      run: cmake --build ${{ env.BUILD_DIR }}

    - uses: actions/upload-artifact@v2
      with:
        name: SimpleLogo_${{ matrix.flavor }}_${{ matrix.compiler.name }}
        path: build/bin/SimpleLogo
        