name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os.name }} ${{ matrix.flavor }} ${{ matrix.compiler.name }}
    runs-on: ${{ matrix.os.label }}

    strategy:
      fail-fast: false
      matrix:
        os: [ {name: "Windows", label: "windows-latest"} ]
        compiler: [ {name: "MSVC", cc: "cl", cxx: "cl"} ]
        flavor: [ Release ]

    env:
      CMAKE_BUILD_TYPE: ${{ matrix.flavor }}
      CMAKE_CONFIG_TYPE: ${{ matrix.flavor }}
      BUILD_DIR: ${{github.workspace}}/build

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      uses: turtlebrowser/get-conan@main

    - name: Install dependencies
      run: |
       mkdir ${{ env.BUILD_DIR }}
       cd ${{ env.BUILD_DIR }}
       conan install .. -s build_type=${{ matrix.flavor }}

    - name: Set environment variables
      shell: bash
      run: echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV
      
    - name: Configure CMake
      run: cmake -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }}

    - name: Build
      run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.CMAKE_CONFIG_TYPE }}

    - uses: actions/upload-artifact@v2
      with:
        name: Windows_${{ matrix.flavor }}_${{ matrix.compiler.name }}
        path: ${{ env.BUILD_DIR }}/bin/SimpleLogo.exe
